### PR TITLE
Make Item properties searchable

### PR DESCRIPTION
**Pull request by IcarusComplex**
I've made all item properties searchable by starting the search argument with `#`.

This allows things like: `#ten storms` to find all characters with Ten Storms set pieces. `#savage` to find everyone wearing Savage Gladiator chain. `#epic` to see all epic items, similar for `#rare` or `#legendary`. 

Additionally, this can be combined with other search arguments, for example: `warrior, #savage` to see all the warriors wearing savage gladiator chain.

### CODE REVIEW

**Comment by IcarusComplex** [comment]
Any update on the PR Pjuske?

**Comment by firecow** [comment]
Oh dear.. Thought it was already in.

**Comment by firecow** [comment]
You have to resolve the merge conflicts, before I can merge it @IcarusComplex

**Comment by firecow** [comment]
Fuck it i'll merge it.

**Pull request merged**
